// src/routes/dashboard/+page.svelte
<script lang="ts">
	import { Button, Loading } from '@veelume/ui';
	import { unwrap } from '$lib/api';
	import { commands, type AccountView } from '$lib/bindings';

	type View =
		| { kind: 'loading' }
		| { kind: 'no-key' }
		| { kind: 'ready'; account: AccountView }
		| { kind: 'error'; message: string };

	let view = $state<View>({ kind: 'loading' });

	async function load() {
		try {
			if (!(await unwrap(commands.getApiKeyStatus()))) {
				view = { kind: 'no-key' };
				return;
			}
			view = { kind: 'ready', account: await unwrap(commands.getAccountInfo()) };
		} catch (e) {
			view = { kind: 'error', message: e instanceof Error ? e.message : String(e) };
		}
	}

	load();
</script>

<div class="mx-auto w-full max-w-3xl space-y-4 p-[var(--density-padding)]">
	<h1 class="text-2xl font-semibold">Dashboard</h1>

	{#if view.kind === 'loading'}
		<Loading />
	{:else if view.kind === 'no-key'}
		<div class="space-y-3 rounded-lg border bg-card p-[var(--density-padding)]">
			<p>Welcome to GW2 Companion! Add an API key to get started.</p>
			<Button href="/settings/api-key">Set up API key</Button>
		</div>
	{:else if view.kind === 'error'}
		<div class="rounded-lg border bg-card p-[var(--density-padding)] text-sm text-destructive">
			{view.message}
		</div>
	{:else}
		{@const acc = view.account}
		<div class="rounded-lg border bg-card p-[var(--density-padding)]">
			<p class="text-lg font-medium">{acc.name}</p>
			<p class="text-sm text-muted-foreground">
				AP: {(acc.daily_ap ?? 0) + (acc.monthly_ap ?? 0)} · WvW Rank: {acc.wvw_rank ?? 'N/A'} ·
				Fractal Level: {acc.fractal_level ?? 'N/A'}
			</p>
		</div>
	{/if}
</div>

// src/views/Dashboard.tsx
import { createResource, type Component, Show } from "solid-js";
import { getApiKeyStatus, getAccountInfo, type Account } from "../lib/api";

const Dashboard: Component = () => {
  const [hasKey] = createResource(getApiKeyStatus);
  const [account] = createResource(
    () => hasKey(),
    async (authenticated) => {
      if (!authenticated) return null;
      try {
        return await getAccountInfo();
      } catch {
        return null;
      }
    }
  );

  return (
    <div>
      <h2
        class="text-2xl font-bold mb-4"
        style={{ color: "var(--gw2-gold)" }}
      >
        Dashboard
      </h2>

      <Show
        when={hasKey()}
        fallback={
          <div
            class="rounded-lg p-6 border border-white/10"
            style={{ "background-color": "var(--gw2-surface)" }}
          >
            <p class="mb-2">
              Welcome to GW2 Companion! Set up your API key in{" "}
              <strong>Settings</strong> to get started.
            </p>
            <p style={{ color: "var(--gw2-muted)" }}>
              You can create an API key at{" "}
              <span class="underline">account.arena.net/applications</span>
            </p>
          </div>
        }
      >
        <Show when={account()} keyed>
          {(acc) => (
            <div
              class="rounded-lg p-6 border border-white/10"
              style={{ "background-color": "var(--gw2-surface)" }}
            >
              <p class="text-lg font-medium">{acc.name}</p>
              <p style={{ color: "var(--gw2-muted)" }}>
                AP: {(acc.daily_ap ?? 0) + (acc.monthly_ap ?? 0)} · WvW Rank:{" "}
                {acc.wvw_rank ?? "N/A"} · Fractal Level:{" "}
                {acc.fractal_level ?? "N/A"}
              </p>
            </div>
          )}
        </Show>
      </Show>
    </div>
  );
};

export default Dashboard;
